apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv1
  labels:
    type: local
spec:
  storageClassName: elasticsearch-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv2
  labels:
    type: local
spec:
  storageClassName: elasticsearch-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
